### ISSUE TITLE
please upgrade imageproc

### ISSUE THREAD

**Issue by hdhoang** [aleozlx/piston-gui#1]
hi! the imageproc version you have in Cargo.lock pulls in nalgebra@0.13, which will no longer compile once rust-lang/rust#49799 is merged. Could you upgrade imageproc and related dependencies to remove the old nalgebra? Thanks!

update: could you do this too with the h5viewer project, that would be great.

**Comment by aleozlx** [comment]
Hi, thanks for reaching out. Noted! Unfortunately, this is just boilerplate code, not even a published package or anything can be relied on, so there probably won't be any fixing.
